### ISSUE TITLE
8.2 issue's

### ISSUE THREAD

**Issue by reaper666735** [funkydude/BasicChatMods#13]
Hello, 

ever since patch 8.2 came out i have been getting "Interface action failed because of an AddOn" (as can be expected :p), but never really getting an error to report ... 

so i enabled the TaintLog and i have been getting these:

Execution tainted by BasicChatMods while reading INTERFACE_ACTION_BLOCKED_SHOWN - Interface\FrameXML\UIParent.lua:5293 DisplayInterfaceActionBlockedMessage()
Interface\FrameXML\UIParent.lua:3188 CheckProtectedFunctionsAllowed()
Interface\FrameXML\UIParent.lua:3200
ShowUIPanel()
Interface\FrameXML\QuestLogOwnerMixin.lua:103 WorldMapFrame:SetDisplayState()
Interface\FrameXML\QuestLogOwnerMixin.lua:41 WorldMapFrame:HandleUserActionToggleSelf()
Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:413 ToggleWorldMap()
TOGGLEWORLDMAP:1

ofc i know the taintlog is not 100% accurate and i have no idea if this is really from BCM, i thought it was still worth to report :p

**Comment by funkydude** [comment]
Also, did this happen during combat?

**Comment by reaper666735** [comment]
it is possible this happened during combat after awhile it's hard to keep it straight :p , 

doing a search i found many seem to be "tainted" by the world map toggle , but ofc  try and pinpoint the culprit xD

**Comment by funkydude** [comment]
You didn't really answer the question in regards to doing a search :D 
Also are you saying you pressed the "M" keybinding and this happened?

**Comment by reaper666735** [comment]
my apologies i must have been reading in a hurry xD , i read i had to look over the Lua errors in the TaintLog for more ToggleWorldMap instances :p

i have Notepad++ for Lua files and the standard windows editors, what did you have in mind ?

**Comment by reaper666735** [comment]
i seem unable to edit my previous post for some reason :p (and uploading a screenshot ...), 

anyway using Notepad++ "Search" function i got a phew hits in the Interface folder:

https://imgur.com/q8L5917

**Comment by funkydude** [comment]
Did you activate something in "classic quest log" when this issue occured?
Does the issue still occur if you disable the "classic quest log" addon?
You will probably need to test this in combat.

**Comment by reaper666735** [comment]
besides the addon being active (works with a small temp fix) i did not activate anything :)

i sometimes do have to disable the addon to see a quest frame, but after re-enabling it i can continue like nothing ever happened so probably a random taint or something

this may be a weird request but could you maybe give some tips/help to Gello (addon author) about this ?, he seems to be having issue's getting this fully fixed ... 

"Curseforge Quote"

Quote from gello3 >>

I've managed to fix many of the SetPoint issues with strategic (and some less-than strategic) use of QuestFrame:ClearAllPoints(), but there are use cases where this is still failing.

The error messages Blizzard provides are not helpful and slathering debug code throughout the addon is not helping to pinpoint the remaining issues.

I'm going to take a break from this for the rest of the day and revisit it when I'm less frustrated.

https://www.curseforge.com/wow/addons/classic-quest-log

so yeah any help would mean the world to us :)


and ty for the continued support with this!

**Comment by funkydude** [comment]
Please stick to the topic:

> Does the issue still occur if you disable the "classic quest log" addon?

**Comment by reaper666735** [comment]
i disabled CQL and went into combat, not getting the same "exact" error but i just got these related to BCM:

Global variable SLASH_BasicChatMods1 tainted by BasicChatMods - Interface\AddOns\BasicChatMods\BasicConfig.lua:101 ?()
7/1 09:50:57.468      Interface\AddOns\BasicChatMods\BasicCore.lua:115 ?()
7/1 09:50:57.468      Interface\AddOns\BasicChatMods\BasicCore.lua:7
7/1 09:50:57.468  Global variable SLASH_SMARTGROUP1 tainted by BasicChatMods - Interface\AddOns\BasicChatMods\smartgroup.lua:13 ?()
7/1 09:50:57.468      Interface\AddOns\BasicChatMods\BasicCore.lua:115 ?()
7/1 09:50:57.468      Interface\AddOns\BasicChatMods\BasicCore.lua:7
7/1 09:50:57.468  Global variable SLASH_SMARTGROUP2 tainted by BasicChatMods - Interface\AddOns\BasicChatMods\smartgroup.lua:14 ?()
7/1 09:50:57.468      Interface\AddOns\BasicChatMods\BasicCore.lua:115 ?()
7/1 09:50:57.468      Interface\AddOns\BasicChatMods\BasicCore.lua:7



Global variable INTERFACE_ACTION_BLOCKED_SHOWN tainted by BasicChatMods - Interface\FrameXML\UIParent.lua:5296 DisplayInterfaceActionBlockedMessage()
7/1 09:51:17.301      Interface\FrameXML\UIParent.lua:3188 CheckProtectedFunctionsAllowed()
7/1 09:51:17.301      Interface\FrameXML\UIParent.lua:3200
7/1 09:51:17.301      ShowUIPanel()
7/1 09:51:17.301      Interface\FrameXML\QuestLogOwnerMixin.lua:103 WorldMapFrame:SetDisplayState()
7/1 09:51:17.301      Interface\FrameXML\QuestLogOwnerMixin.lua:41 WorldMapFrame:HandleUserActionToggleSelf()
7/1 09:51:17.301      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:413 ToggleWorldMap()
7/1 09:51:17.301      TOGGLEWORLDMAP:1



Execution tainted by BasicChatMods while reading INTERFACE_ACTION_BLOCKED_SHOWN - Interface\FrameXML\UIParent.lua:5293 DisplayInterfaceActionBlockedMessage()
7/1 09:51:19.983      Interface\FrameXML\UIParent.lua:3188 CheckProtectedFunctionsAllowed()
7/1 09:51:19.983      Interface\FrameXML\UIParent.lua:3200
7/1 09:51:19.983      ShowUIPanel()
7/1 09:51:19.983      Interface\FrameXML\QuestLogOwnerMixin.lua:103 WorldMapFrame:SetDisplayState()
7/1 09:51:19.983      Interface\FrameXML\QuestLogOwnerMixin.lua:51 WorldMapFrame:HandleUserActionToggleQuestLog()
7/1 09:51:19.983      Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:409 ToggleQuestLog()
7/1 09:51:19.983      TOGGLEQUESTLOG:1

could easily be another addon tainting more BCM into the mix ...

**Comment by reaper666735** [comment]
looking for similarities in the errors like you showed me earlier i found another addon and disabling that one removes all but one taint:

Global variable SLASH_BasicChatMods1 tainted by BasicChatMods - Interface\AddOns\BasicChatMods\BasicConfig.lua:101 ?()
7/1 10:04:24.021      Interface\AddOns\BasicChatMods\BasicCore.lua:115 ?()
7/1 10:04:24.021      Interface\AddOns\BasicChatMods\BasicCore.lua:7
7/1 10:04:24.021  Global variable SLASH_SMARTGROUP1 tainted by BasicChatMods - Interface\AddOns\BasicChatMods\smartgroup.lua:13 ?()
7/1 10:04:24.021      Interface\AddOns\BasicChatMods\BasicCore.lua:115 ?()
7/1 10:04:24.021      Interface\AddOns\BasicChatMods\BasicCore.lua:7
7/1 10:04:24.021  Global variable SLASH_SMARTGROUP2 tainted by BasicChatMods - Interface\AddOns\BasicChatMods\smartgroup.lua:14 ?()
7/1 10:04:24.021      Interface\AddOns\BasicChatMods\BasicCore.lua:115 ?()
7/1 10:04:24.021      Interface\AddOns\BasicChatMods\BasicCore.lua:7

**Comment by funkydude** [comment]
1. What was the other addon?
2. You can safely ignore the "slash" stuff, that's normal.
3. Does this error actually show in game or only in the framexml log file?

**Comment by reaper666735** [comment]
1. Classic Guild Frame
2. ok
3. TaintLog , framexml log is empty as i mentioned i only get the yellow text with "interface action failed because of an addon" so no LUA error frame showed up

but it's safe to say BCM is clear from issue's , it seems 1-2 other addons just prompt the mixup ( besides the SLASH stuff i should ignore :p)

**Comment by funkydude** [comment]
Try re-enabling the quest log addon and see if you still have the issue. It might just be the guild frame addon causing it.

**Comment by reaper666735** [comment]
it's been awhile and no issue's so i know now it's not BCM ^^, ty for all your help

**Comment by funkydude** [comment]
You didn't actually answer if you re-enabled the quest log addon or not so we can see if it's just the guild frame addon or both.

**Comment by funkydude** [comment]
I've pushed a new release to try prevent BCM from being blamed from similar issues.
