### ISSUE TITLE
Copy Chat: wrong line selected

### ISSUE THREAD

**Issue by reaper666735** [funkydude/BasicChatMods#14]
Hello, 

i seem to have stumbled on an issue with the Copy Chat feature (and pray it's not because of a taint from another addon this time xD), so basically i can still copy text but BCM is about several lines too high... 

As you can see in this picture:
![image](https://user-images.githubusercontent.com/16833/61177859-3c50f100-a5d7-11e9-8889-182ad0cb8e01.png)

I'm trying to copy the greyed section as a test but the actual line selected by BCM is 18 lines higher (you can see the white dash behind the word 'Trouble.' 

ty.

**Comment by funkydude** [comment]
Sounds like you are describing this wow bug: https://github.com/Stanzilla/WoWUIBugs/issues/1

**Comment by funkydude** [comment]
Should be resolved as of WoW patch 8.3
