### ISSUE TITLE
PvE LFG panel tainted and blocked in combat

### ISSUE THREAD

**Issue by Wolryr** [funkydude/BasicChatMods#15]
**Describe the bug**

This is super weird, but when using BasicChatMods, sometimes in combat when I try to open the LFG PvE (Premade panel) from the 'eye button' via the Objective tracker I'd get a 'Interface action blocked due to an AddOn' message, and said panel won't open. _(See link to the picture -sorry, I still don't know how to attach pictures here)._ It will remain blocked until I either drop combat or run a /reload. Seems to be another of those new protected frames in patch 8.2, but sounds really weird since I wouldn't imagine BasicChatMods messing with that. I'm no expert in any way, though.

https://i.imgur.com/Frc6Q8R.jpg

**Do you have an error log of what happened?**

I do have the /console taintlog 11 message related:

>Execution tainted by BasicChatMods while reading INTERFACE_ACTION_BLOCKED_SHOWN - Interface\FrameXML\UIParent.lua:5293 DisplayInterfaceActionBlockedMessage()
Interface\FrameXML\UIParent.lua:3188 CheckProtectedFunctionsAllowed()
Interface\FrameXML\UIParent.lua:3200
ShowUIPanel()
Interface\FrameXML\PVEFrame.lua:129 PVEFrame_ShowFrame()
Interface\FrameXML\PVEFrame.lua:87 PVEFrame_ToggleFrame()
TOGGLEGROUPFINDER:1
Execution tainted by BasicChatMods while reading INTERFACE_ACTION_BLOCKED_SHOWN - Interface\FrameXML\UIParent.lua:5293 DisplayInterfaceActionBlockedMessage()
Interface\FrameXML\UIParent.lua:3188 CheckProtectedFunctionsAllowed()
Interface\FrameXML\UIParent.lua:3200
ShowUIPanel()
Interface\FrameXML\PVEFrame.lua:129 PVEFrame_ShowFrame()
Interface\FrameXML\LFGList.lua:370 LFGListFrame_BeginFindQuestGroup()
Interface\FrameXML\LFGList.lua:3282 LFGListUtil_FindQuestGroup()
Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTrackerShared.lua:151

**To Reproduce**

Since I can temporally "get rid" of it by doing a /reload, it's tricky to consistently trigger it, but I've tried to narrow it down by disabling any other AddOn, entering combat and then clicking the eye thing.

**BasicChatMods Version**

Most updated version currently in Curseforge.

**Comment by Wolryr** [comment]
UPDATE: After long testing, I've seem to have narrow it down to another AddOn, TomTom. My apologies.

**Comment by funkydude** [comment]
Thanks for investigating.
I've also pushed a new release to try prevent BCM from being blamed from similar issues.
