### ISSUE TITLE
Classic WoW Error - "attempt to index global 'QuickJoinToastButton' (a nil value)"

### ISSUE THREAD

**Issue by Reubensandvich** [funkydude/BasicChatMods#18]
Message: Interface\AddOns\BasicChatMods\fade.lua:175: attempt to index global 'QuickJoinToastButton' (a nil value)
Time: Sat Aug 10 02:16:40 2019
Count: 7179
Stack: Interface\AddOns\BasicChatMods\fade.lua:175: attempt to index global 'QuickJoinToastButton' (a nil value)
Interface\AddOns\BasicChatMods\fade.lua:175: in function <Interface\AddOns\BasicChatMods\fade.lua:157>

Locals: (for index) = 1
(for limit) = 10
(for step) = 1
i = 1
chatFrame = ChatFrame1 {
 GatherSelectedText = <function> defined =[C]:-1
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 tellTimer = 108320.242000
 fadeDurationSecs = 3
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 ScrollToBottom = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 GetIndentedWordWrap = <function> defined =[C]:-1
 buttonSide = "left"
 GetFont = <function> defined =[C]:-1
 checkedGMOTD = true
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 OnPostUpdate = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 textIsCopyable = false
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 overrideFadeTimestamp = 0
 MarkDisplayDirty = <function> defined =[C]:-1
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 fontStringPool = <table> {
 }
 CanEffectivelyFade = <function> defined =[C]:-1
 OnPreSizeChanged = <function> defined =[C]:-1
 GetScrollOffset = <function> defined =[C]:-1
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 name = "General"
 CalculateLineSpacing = <function> defined =[C]:-1
 AddMessage = <function> defined =[C]:-1
 InitializeFontableFrame = <function> defined =[C]:-1
 GetShadowColor = <function> defined =[C]:-1
 isUninteractable = false
 SetOnTextCopiedCallback = <function> defined =[C]:-1
 RemoveMessagesByPredicate = <function> defined =[C]:-1
 TransformMessages = <function> defined =[C]:-1
 SetClampRectInsets = <function> defined =[C]:-1
 SetShadowColor = <function> defined =[C]:-1
 buttonFrame = ChatFrame1ButtonFrame {
 }
 HasFontObject = <function> defined =[C]:-1
 isDocked = 1
 GetOnTextCopiedCallback = <function> defined =[C]:-1
 SetFading = <function> defined =[C]:-1
 OnPostHide = <function> defined =[C]:-1
 alternativeDefaultLanguage = "Common"
 isInitialized = 1
 GetNumVisibleLines = <function> defined =[C]:-1
 GetInsertMode = <function> defined =[C]:-1
 SetTimeVisible = <function> defined =[C]:-1
 hasOwnFontObject = true
 Clear = <function> defined =[C]:-1
 oldAlpha = 0
 channelList = <table> {
 }
 GetTimeVisible = <function> defined =[C]:-1
 MarkLayoutDirty = <function> defined =[C]:-1
 SetTextCopyable = <function> defined =[C]:-1
 BackFillMessage = <function> defined =[C]:-1
 UnpackageEntry = <function> defined =[C]:-1
 FontStringContainer = <unnamed> {
 }
 SetShadowOffset = <function> defined =[C]:-1
 messageTypeList = <table> {
 }
 flashTimer = 0
 timeVisibleSecs = 120
 PackageEntry = <function> defined =[C]:-1
 MakeFontObjectCustom = <function> defined =[C]:-1
 fontObject = table: 00000296594156A0 {
 }
 SetInsertMode = <function> defined =[C]:-1
 UpdateSelectingText = <function> defined =[C]:-1
 zoneChannelList = <table> {
 }
 SetScrollOffset = <function> defined =[C]:-1
 onDisplayRefreshedCallback = <function> defined =[C]:-1
 insertMode = 2
 ResetSelectingText = <function> defined =[C]:-1
 GetTextColor = <function> defined =[C]:-

**Comment by funkydude** [comment]
Fixed.
