### ISSUE TITLE
All changes not saving after session

### ISSUE THREAD

**Issue by JuanLargearm** [funkydude/BasicChatMods#20]
Addon works great, however *any* changes made do not stick after the session. 

After logout all are back to default on next login. Using the Reload UI command also just reverts all changes back to default.

**Comment by funkydude** [comment]
Works fine here, will need more info. Have you tried disabling your other addons?

**Comment by JuanLargearm** [comment]
I did try disabling addons as I suspected this could be a conflict. Also made sure all files in the addons directory were not read only just in case. Didn't find the issue so tried a similar addon which works with no problems and am using that now instead. Not sure what caused this problem.
