### ISSUE TITLE
URL copying for links ending in '.gg'

### ISSUE THREAD

**Issue by Xorag** [funkydude/BasicChatMods#25]
This is just an enhancement request for the URL copy to include URLs ending in '.gg' such as discord invites:

discord.gg/123ABC
https://discord.gg/123ABC

Thanks!

**Comment by funkydude** [comment]
I cannot reproduce this problem. Tested in game and it works fine.
BCM doesn't really care what domain you use, it searches patterns.
You can try disabling all your other addons to see if it's a conflict with another addon.

**Comment by Xorag** [comment]
That's what I figured, I'll take another look, possibly the URL sent to me the other day had erroneous spaces or something.

**Comment by Xorag** [comment]
As an update - I discovered the issue, the URLs aren't clickable when they are in raid warning - other channels are fine. Thanks!
