### ISSUE TITLE
Text color in copy chat frame

### ISSUE THREAD

**Issue by bullsei** [funkydude/BasicChatMods#3]
Hi, i noticed that the color of each message in the copy chat frame doesn't match the color of the message in the chat frame
![image](https://user-images.githubusercontent.com/16833/30385785-1618b9a0-98a0-11e7-80b3-458ed6388ebe.png)

**Comment by reaper666735** [comment]
i can confirm this is still happening, just a small issue :)

![wowscrnshot_092717_102036](https://user-images.githubusercontent.com/5812860/30903091-df945dca-a36d-11e7-834a-ecd9e7d73f08.jpg)

**Comment by funkydude** [comment]
Either fixed, no longer happens, or was never able to reproduce.
