### ISSUE TITLE
SetBackdrop error caused by change in Blizzard Code for Shadowlands (9.0)

### ISSUE THREAD

**Issue by arcadepro** [funkydude/BasicChatMods#30]
Blizz has changed how Frame/SetBackdrop is implemented which causes the addon to crash.

The following quick changes will work for now. 

\World of Warcraft\_beta_\Interface\AddOns\BasicChatMods\BasicCore.lua (1 hit)

	Line 34: 	local frame = CreateFrame("Frame", nil, UIParent, BackdropTemplateMixin and "BackdropTemplate")
  

\World of Warcraft\_beta_\Interface\AddOns\BasicChatMods\chatcopy.lua (1 hit)

	Line 46: 	local frame = CreateFrame("Frame", "BCMCopyFrame", UIParent, BackdropTemplateMixin and "BackdropTemplate")

**Comment by funkydude** [comment]
Fixed.
