### ISSUE TITLE
LUA error when trying to invite via alt-clicking a friend's battletag in chat.

### ISSUE THREAD

**Issue by dle0105** [funkydude/BasicChatMods#34]
2x BasicChatMods\AltInvite.lua:12: Usage: C_PartyInfo.InviteUnit(targetName)
[string "=[C]"]: ?
[string "@BasicChatMods\AltInvite.lua"]:12: in function <BasicChatMods\AltInvite.lua:9>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetItemRef'
[string "@FrameXML\ChatFrame.lua"]:3906: in function `ChatFrame_OnHyperlinkShow'
[string "*:OnHyperlinkClick"]:1: in function <[string "*:OnHyperlinkClick"]:1>
[string "=[C]"]: ?

Locals:
(*temporary) = nil

**Comment by funkydude** [comment]
Interesting. This has probably been a problem for a while. It works with all non-Bnet related stuff, guess I never thought to test bnet chat. Looking into it.

**Comment by dle0105** [comment]
> 
> 
> Interesting. This has probably been a problem for a while. It works with all non-Bnet related stuff, guess I never thought to test bnet chat. Looking into it.

I think you may be right, as it does look familiar to me. I guess I just never got around to reporting it until now.

Thanks for the quick response.

**Comment by funkydude** [comment]
Thanks for the report, fixed in the latest release.
