### ISSUE TITLE
PMs only show in their own chat window since a few months ago

### ISSUE THREAD

**Issue by Booggg** [funkydude/BasicChatMods#36]
## Describe the problem

PMs only show in their own chat window since a few months ago, regardless if the chat channel has wispers selected or not
### What steps will reproduce the problem?

1.  
2.  
3.

**Comment by funkydude** [comment]
This is not a BCM issue, but a WoW issue. Change your "New Whispers" setting:
![image](https://user-images.githubusercontent.com/16833/108387115-34225400-7205-11eb-8b4a-bf4ca5f9e745.png)
