### ISSUE TITLE
Settings not saving 

### ISSUE THREAD

**Issue by Samidaro** [funkydude/BasicChatMods#37]
Hi, am having a problem with the font not saving when i logout. I did it first on my main and it stuck. On my alts every time i set it to something and relog/reload, the change is gone. Any way i can fix that please? 
Thansk for the addon.

**Comment by msc6399** [comment]
Same issue with Dragonflight Beta

**Comment by funkydude** [comment]
Not a BCM issue, disable your other addons until you find what's causing it.
