### ISSUE TITLE
Alt-Click Not Working

### ISSUE THREAD

**Issue by Incarceron** [funkydude/BasicChatMods#39]
## Describe the problem
I have enabled the alt-click setting for BCM and it will not work. I do not have any other chat mods installed.

### What steps will reproduce the problem?

1.  Enable alt-click in settings
2.  alt-click on a name
3.  edit box opens instead of inviting

### What version of the addon are you using? (Stating 'latest' is not useful)
v1-bcc

**Comment by funkydude** [comment]
Fixed, thanks.
