### ISSUE TITLE
Global variable object tainted

### ISSUE THREAD

**Issue by Laumesis** [funkydude/BasicChatMods#41]
`object` is not defined as local variable in this scope, so this taints global one.
`Global variable object tainted by BasicChatMods - Interface\AddOns\BasicChatMods\fade.lua:131`

https://github.com/funkydude/BasicChatMods/blob/28656812bdc2270b6fc2b88c7cfa39314c4655cf/fade.lua#L131
https://github.com/funkydude/BasicChatMods/blob/28656812bdc2270b6fc2b88c7cfa39314c4655cf/fade.lua#L137
https://github.com/funkydude/BasicChatMods/blob/28656812bdc2270b6fc2b88c7cfa39314c4655cf/fade.lua#L143

Sorry, I'm too lazy to fork and to make PR :(

**Comment by funkydude** [comment]
Thanks!
