### ISSUE TITLE
10.0 error when opening Edition Mode

### ISSUE THREAD

**Issue by Romsh** [funkydude/BasicChatMods#59]
## Describe the problem
When you open the Edition Mode with the Pre Patch of DragonFlight, there's a message saying that BasicChatMods is blocked. 

### What steps will reproduce the problem?

1.  In retail, on 10.0, open the Edition Mode
2.  
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![image](https://user-images.githubusercontent.com/16833/198279857-4af3e3d3-3912-4a25-89bd-ed0d8bd93a77.png)

### Do you have an error log of what happened?
v10.0.0

### Any additional information? (example: WoW language if not English)
Wow language in French.

**Comment by funkydude** [comment]
This isn't a BCM issue, but you can just type `/reload` in chat to reload UI and it resolves this.
