### ISSUE TITLE
information on chat issue

### ISSUE THREAD

**Issue by reaper666735** [funkydude/BasicChatMods#6]
Hello, 

i have not seen any other way to contact you outside of curse private msg, i'm not very used to Github :).
and sorry that i'm making an "issue" thread.. .

anyway i just wanted some clarification on something that started since 7.3 hit, 

each time somebody logs on/off from Battlenet the icons don't show till you refresh the chat window by scrolling up and down,

![wowscrnshot_091717_140309](https://user-images.githubusercontent.com/5812860/30903393-ed30442a-a36e-11e7-81d9-3b4e6c04e493.jpg)

so i'm wondering if this is a native 7.3 bug or something todo with BCM :)

ty.

**Comment by funkydude** [comment]
7.3 bug unfortunately.

**Comment by reaper666735** [comment]
ah ok :), then we will just have to hope it gets fixed with time :p

ty.
