### ISSUE TITLE
[Feature Request] Chat Command History

### ISSUE THREAD

**Issue by Quartzfire** [funkydude/BasicChatMods#66]
A nice option would be to save a history of things you recently types to make it easier to re-input the chat.

A use case might be if you do something like "/tar <NPC>" in chat. If this chat entry was saved, you could press enter to type new chat, press up bottom to scroll through the previous X many things you typed, and press enter to re-use a previous chat entry.

**Comment by funkydude** [comment]
Hold down ALT and use up/down arrows.
