### ISSUE TITLE
Player Names in /me

### ISSUE THREAD

**Issue by FireAllianceNX** [funkydude/BasicChatMods#67]
### What steps will reproduce the problem?

Linking an item while using /me emote (from anyone) will put the level, class color on the item, and raid group after the item name. The class names would be on the item names and the rarity color of the item sits on the brackets, character level and raid group if in raid.

### What version of the addon are you using? (Stating 'latest' is not useful)
10.0.0

### Do you have an error log of what happened?
N/A

### Any additional information? (example: WoW language if not English)
Probably don't need the Player Names modifications on the emotes line if it's possible to exclude it.

**Comment by FireAllianceNX** [comment]
Apparently also does it on any oRA announcement about feast and cauldron links

**Comment by funkydude** [comment]
Please post a screenshot of the oRA specific issue.

**Comment by funkydude** [comment]
Nevermind. Pushed a new release to fix the emotes. Hopefully it also fixes oRA but let me know if it doesn't!

**Comment by FireAllianceNX** [comment]
oRA fixed along with it, awesome!
Thanks!
