### ISSUE TITLE
Hide 'Text To Speech' button

### ISSUE THREAD

**Issue by rakkarage** [funkydude/BasicChatMods#71]
## Describe the problem
the Button hide option says it hides the chat frame side buttons but if you enable text to speech another button appears
posibble to hide this too? please and thanks!

### What steps will reproduce the problem?

1.  enable tts
2.  new button pushes chat to right
3.  profit

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![WoWScrnShot_111522_225517](https://user-images.githubusercontent.com/962340/202080288-b5769fa8-b0a4-4542-abc2-abcb498a65a5.jpg)

### What version of the addon are you using? (Stating 'latest' is not useful)

BasicChatMods-v10.0.2.zip

**Comment by funkydude** [comment]
Where are you enabling this?

**Comment by rakkarage** [comment]
Sorry. Options->Text To Speech
![WoWScrnShot_112022_125856](https://user-images.githubusercontent.com/962340/202918058-9dd0baf5-32ca-460c-b04b-5fbcd31cb915.jpg)
Thanks!

**Comment by funkydude** [comment]
Thanks!
