### ISSUE TITLE
Lagspike from rep gain

### ISSUE THREAD

**Issue by PeterRenaertsPXL** [funkydude/BasicChatMods#72]
## Describe the problem
Whenever I gain rep (be it from a quest, world quest, looting a raid boss's "rep token" or from killing mobs) there's a second lagspike.

### What steps will reproduce the problem?

1.  Turn addon on
2.  Gain rep through any means (very noticeable when doing TBC dungeons)
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
10.0.2

### Any additional information? (example: WoW language if not English)
English client

**Comment by funkydude** [comment]
No valuable reproduction steps are provided here.
If this actually was an issue, I would be flooded with reports of it.

Try disabling all your other addons and the issue will probably go away. Do this slowly and you can identify the culprit.
