### ISSUE TITLE
BasicChatMods is sorted wrong in options?

### ISSUE THREAD

**Issue by rakkarage** [funkydude/BasicChatMods#74]
## Describe the problem
Not a big deal but most mods seem to be sorted alphabetically, not BasicChatMods? spent an extra 10 seconds looking for it...

### What steps will reproduce the problem?

1.  open Options->Addons
2.  note order

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![WoWScrnShot_112322_115036](https://user-images.githubusercontent.com/962340/203604230-dbc3546d-148d-4bc4-a73f-80d029a48e7d.jpg)

### What version of the addon are you using? (Stating 'latest' is not useful)

BasicChatMods-v10.0.3.zip

Thanks!

**Comment by rakkarage** [comment]
I just found out how that works...

https://wowpedia.fandom.com/wiki/Using_the_Interface_Options_Addons_panel

```
InterfaceOptions_AddCategory(panel [, addOn, position])
Adds a configuration panel.
panel
[Frame](https://wowpedia.fandom.com/wiki/UIOBJECT_Frame) - A panel with widgets (children) to control an AddOn.
addOn
boolean? - Identifies an AddOn is from a third party; however, the argment has no effect because the function body checks [issecure](https://wowpedia.fandom.com/wiki/API_issecure)().
position
number? - Position in the list of panels; omitting defaults to **alphabetical** order.
```

**Comment by funkydude** [comment]
I don't specify a position so I don't know why it would be sorted like that. But it's clearly not the only addon doing that for you, for some reason.

**Comment by mbattersby** [comment]
The game doesn't seem to sort them, they go in the order they're added. Game seems to be relying on alphabetical loading order to get it right, and expecting you not to delay registering your panel until a later event.
