### ISSUE TITLE
channelnames.lua doesn't take trade/services into account

### ISSUE THREAD

**Issue by tlundse** [funkydude/BasicChatMods#76]
In dragonflight, when in a city, there seems to be two channels matching the trade-regexp, the regular trade and the services channel.
Because of how the matching works, they both end up getting translated to whatever name you select for the regular trade.

**Comment by tlundse** [comment]
Here are the channels I am on, after HS to stormwind:
[1. General - Stormwind City]
[2. Trade - City]
[3. LocalDefense - Stormwind City]
[4. Trade (Services) - City]

**Comment by tlundse** [comment]
Hacked support for this locally, which is, ofc, trivial - the issue is backwards-compatibility with SavedVariables. :(

**Comment by Tarkumi** [comment]
Hello,

Could you write, hogy you hacked ?

Thanks.
