### ISSUE TITLE
Constant Errors At Login for 10.1

### ISSUE THREAD

**Issue by yajinni** [funkydude/BasicChatMods#85]
3438x BasicChatMods/fade.lua:175: attempt to call method 'IsDraggingThumb' (a nil value)
[string "@BasicChatMods/fade.lua"]:175: in function <BasicChatMods/fade.lua:164>

Locals:
(for index) = 1
(for limit) = 10
(for step) = 1
i = 1
chatFrame = ChatFrame1 {
 SetJustifyV = <function> defined =[C]:-1
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 GetSnapOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:532
 EditMode_OnResized = <function> defined @FrameXML/EditModeSystemTemplates.lua:1747
 systemInfo = <table> {
 }
 OnFontObjectUpdated = <function> defined =[C]:-1
 OnKeyDown = <function> defined @FrameXML/EditModeSystemTemplates.lua:81
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 BaseAddMessage = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 ScrollToBottom = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 GetSelectionOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:463
 ResetToDefaultPosition = <function> defined @FrameXML/EditModeSystemTemplates.lua:233
 GetScaledSelectionSides = <function> defined @FrameXML/EditModeSystemTemplates.lua:455
 GetIndentedWordWrap = <function> defined =[C]:-1
 SelectSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:686
 GetFont = <function> defined =[C]:-1
 GetFrameMagneticEligibility = <function> defined @FrameXML/EditModeSystemTemplates.lua:637
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 OnPostUpdate = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 IsBelowFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:422
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @FrameXML/EditModeSystemTemplates.lua:344
 GetScaledCenter = <function> defined @FrameXML/EditModeSystemTemplates.lua:448
 overrideFadeTimestamp = 0
 DoesSettingDisplayValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:368
 MarkDisplayDirty = <function> defined =[C]:-1
 UpdateDisplayInfoOptions = <function> defined @FrameXML/EditModeSystemTemplates.lua:379
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 ProcessMovementKey = <function> defined @FrameXML/EditModeSystemTemplates.lua:39
 GetSettingValueBool = <function> defined @FrameXML/EditModeSystemTemplates.lua:359
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 fontStringPool = <table> {
 }
 DoesSettingValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:363
 CanEffectivelyFade = <function> defined =[C]:-1
 ShouldResetSettingsDialogAnchors = <function> defined @FrameXML/EditModeSystemTemplates.lua:172
 OnPreSizeChanged = <function> defined =[C]:-1
 dirtySettings = <table> {
 }
 OnPostMouseUp = <function> defined =[C]:-1
 IsToTheLeftOfFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:404
 GetSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:388
 hasActiveChanges = false
 OnSystemLoad = <function> defined @FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @FrameXML/EditModeSystemTemplates.lua:576
 GetCombinedCenterOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:519
 SetupSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:332
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 SetPointBase = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 UpdateSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:293
 CalculateLineSpacing = <function> defined =[C]:-1
 AddMessa

**Comment by Dmeister406** [comment]
Was about to log this error as well. Event triggers multiple times per second.

**Comment by Virond** [comment]
FYI - going into /bcm and disabling Fade appears to fix the issue as a temporary work around until it is updated.
