### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by dboyraz** [funkydude/BasicChatMods#87]
Error from Bug Grabber

1x [ADDON_ACTION_BLOCKED] AddOn 'BasicChatMods' tried to call the protected function 'MultiBarBottomRightButton1:SetShown()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetShown'
[string "@FrameXML/ActionBar.lua"]:196: in function `UpdateShownButtons'
[string "@FrameXML/ActionButton.lua"]:351: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:809: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:200: in function <FrameXML/ActionButton.lua:197>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506

**Comment by funkydude** [comment]
This isn't a Lua error, it's a taint issue.
You can ignore it unless it's preventing you from doing something, at which point you can just type /reload to fix it.
Currently still trying to track the real cause down, but it's likely an issue on Blizzard's end that they will need to fix.
