### ISSUE TITLE
No received currency message 

### ISSUE THREAD

**Issue by wittleanow** [funkydude/BasicChatMods#88]
## Describe the problem
Let's say a boss goes down, upon looting or if the ML loots, will let you know you received a share of 30 gold, as well as the loot that dropped (Considering you have all these checked to show in your chat settings) and SHOULD also let you know, received x2 Emblems of Conquest, or x1 Sidereal Essence, or x1 Champion's seal but that is somehow blocked and is the only loot I am unable to see in the chat. Currencies is the only thing it won't allow to show up in chat, but I am still receiving them as I can just C tab to check. 

### What steps will reproduce the problem?

1.  
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
[v10.1.3](https://github.com/funkydude/BasicChatMods/tree/v10.1.3) (2023-06-21)

### Do you have an error log of what happened?
I do not, as it doesn't really cause problems to my UI it is just the lack of logging what I received as far as currency.

### Any additional information? (example: WoW language if not English)
I did check to make sure I was checked in the settings to show what I loot and all that and I do see it all in chat but if I receive any of the currencies it just doesn't show! I love this ad on it's very light weight and simple :)

**Comment by funkydude** [comment]
This addon doesn't make any judgement on what messages it customizes. Anything sent to chat, gets customized. So it's unlikely to be anything related to this addon. It doesn't decide "hey, this is a loot message, I will treat this differently."

However if you can provide before & after screenshots proving that BCM is at fault, with ONLY BCM enabled and no other addons, I can move forward with looking into this issue.

**Comment by funkydude** [comment]
No response, closing.
