### ISSUE TITLE
Chat Channels Keep Resetting

### ISSUE THREAD

**Issue by iwawashi** [funkydude/BasicChatMods#89]
Upon logging out and back in, all chat window channels are reset to all channels selected (Trade, Local Defense, etc.).  You can change these in game.  However, once you log out and back in, they are all selected in each window once again.

**Comment by AMKN75** [comment]
I have the same issue since last reset. Exactly as explained by OP.

**Comment by iwawashi** [comment]
So it turned out that this was a Blizzard bug (which they recently fixed) and not a addon issue.  My apologies - issue closed.
