### ISSUE TITLE
Taint

### ISSUE THREAD

**Issue by Doctor0Who** [funkydude/BasicChatMods#9]
Date: 2018-10-08 14:37:55
ID: 1
Error occured in: AddOn: BasicChatMods
Count: 1
Message: Error: AddOn BasicChatMods attempted to call a forbidden function (GuildControlSetRank()) from a tainted execution path.
Debug:
   [C]: GuildControlSetRank()
   ...\Blizzard_GuildControlUI\Blizzard_GuildControlUI.lua:24:
      ...\Blizzard_GuildControlUI\Blizzard_GuildControlUI.lua:7
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:692: Communities_LoadUI()
   ..\FrameXML\UIParent.lua:926: ToggleCommunitiesFrame()
   ..\FrameXML\UIParent.lua:813:
      ..\FrameXML\UIParent.lua:792

**Comment by Doctor0Who** [comment]
Any update or fix for this?

**Comment by funkydude** [comment]
Nothing I can do about this, It's a Blizz issue. Typing /reload after this kind of taint should resolve it.
