### ISSUE TITLE
[Minor bug report] BCM not sorted correctly in the addon options menu

### ISSUE THREAD

**Issue by Sluimerstand** [funkydude/BasicChatMods#91]
## Describe the problem
BCM is not sorted alphabetically in the addon settings menu. I keep looking for it where I expect the B to be.

### What steps will reproduce the problem?
1.  Open Options,

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://github.com/user-attachments/assets/1be194c5-85c7-4bd0-b7ba-86d014a5a0cf)

### What version of the addon are you using? (Stating 'latest' is not useful)
v10.2.7

### Do you have an error log of what happened?
N/A

### Any additional information? (example: WoW language if not English)
N/A

**Comment by funkydude** [comment]
This is an issue with the game, not BCM
